version: '3.8'

services:
  nginx-gateway:
    image: openresty/openresty:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - neo-mall
      - neo-status
      - neo-dev
    restart: always

  neo-status:
    image: nginx:alpine
    volumes:
      - ./site-a-status:/usr/share/nginx/html:ro
      - ./site-a-status/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  neo-dev:
    image: nginx:alpine
    volumes:
      - ./site-b-dev:/usr/share/nginx/html:ro
      - ./site-b-dev/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  neo-mall:
    build: ./site-c-mall
    restart: always

  neo-ftp:
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./site-d-ftp:/home/ftpuser/
    environment:
      PUBLICHOST: 192.168.17.133
      # 停用所有安全機制
      TLS: 0
      # 允許匿名登入
      FTP_ANONYMOUS_ARE_ALLOWED: "yes"
      # 對應到內建的 ftp 使用者目錄
      FTP_USER_HOME: /home/ftpuser
    restart: always
