background=NO
anonymous_enable=YES
no_anon_password=YES
local_enable=NO
write_enable=NO
anon_root=/home/vsftpd/anonymous
chroot_local_user=YES
allow_writeable_chroot=YES
hide_ids=YES
xferlog_enable=YES
xferlog_file=/var/log/vsftpd/vsftpd.log
seccomp_sandbox=NO
listen=YES
listen_ipv6=NO
