background=NO
anonymous_enable=YES
no_anon_password=YES
local_enable=NO
write_enable=NO
anon_root=/home/vsftpd/anonymous
chroot_local_user=YES
allow_writeable_chroot=YES
pasv_enable=YES
pasv_address=192.168.17.133
pasv_min_port=30000
pasv_max_port=30009
pasv_addr_resolve=NO
port_enable=YES
connect_from_port_20=YES
ftp_data_port=20
hide_ids=YES
xferlog_enable=YES
xferlog_file=/var/log/vsftpd/vsftpd.log
seccomp_sandbox=NO
listen=YES
listen_ipv6=NO
