server {
    listen 80;
    root /var/www/html;
    index index.php;

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass neo-php:9000;
        include fastcgi_params;
        # 刻意不加 try_files，製造漏洞條件
    }
}
